services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  airflow-init:
    image: apache/airflow:2.10.5
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres/airflow
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Shanghai
    volumes:
      - ./config:/opt/airflow/config
      - ./requirements.txt:/opt/airflow/requirements.txt
    entrypoint: ["bash", "-c", "pip install --no-cache-dir -r requirements.txt && airflow db check-migrations || airflow db init && airflow users list | grep -q admin || airflow users create --username admin --password ${ADMIN_PASSWORD} --firstname Fang --lastname Yongchao --role Admin --email ${ADMIN_EMAIL}"]
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres/airflow
      - AIRFLOW__WEBSERVER__WORKERS=4
      - AIRFLOW__WEBSERVER__PORT=8080
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./requirements.txt:/opt/airflow/requirements.txt
    entrypoint: ["bash", "-c", "pip install --no-cache-dir -r requirements.txt && airflow webserver"]
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    image: apache/airflow:2.10.5
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres/airflow
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Shanghai
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./include:/opt/airflow/include
      - ./requirements.txt:/opt/airflow/requirements.txt
    entrypoint: ["bash", "-c", "pip install --no-cache-dir -r requirements.txt && airflow scheduler"]
    depends_on:
      airflow-init:
        condition: service_completed_successfully